Feature/3
gpb-it-factory/berezina-telegram-bot pull request #4
Opened 2024-05-28 23:46 UTC by sabina-ber

В этом пулл-реквесте я создала скелет Telegram-бота, следуя принципам Onion Architecture. Были добавлены следующие слои и компоненты:

### Domain Layer:

Models: Созданы базовые модели User и Wallet.

### Application Layer:

Command Strategies: Реализован паттерн "Стратегия" для обработки команд. Добавлена команда /ping, которая отвечает pong.
Command Handler: Создан обработчик команд, который использует стратегии для выполнения команд.

### Infrastructure Layer:

BotConfig.java: Конфигурация для инициализации бота.
CommandConfig.java: Конфигурация для настройки команд.
DotenvConfig.java: Конфигурация для загрузки переменных окружения.

### Logging:

logback-spring.xml: Конфигурационный файл для настройки логгера.

Добавлена настройка логгера с использованием slf4j и logback. Логи сохраняются в файлы.

2024-06-03 18:13 UTC, vaganov-vadim requested changes
Привет! В целом всё здорово, но есть моменты, где можно сделать совсем круто. Оставил комменты, давай подумаем над ними.

2024-06-03 18:13 UTC, vaganov-vadim commented on src/main/java/com/sabinaber/berezinabot/BerezinaBotApplication.java
> +	private final Dotenv dotenv;
А что это за штука?) Впервые вижу. Расскажи в паре слов что и зачем.

2024-06-03 18:13 UTC, vaganov-vadim commented on src/main/java/com/sabinaber/berezinabot/adapters/bot/TelegramBot.java
> +        if (messageText.startsWith("/createuser")) {
Вот такая штука выглядит не очень расширяемо. Если будет 100 команд, то у нас тут будет 100 if-else?) И ещё это в командной разработке может стать местом для постоянных конфликтов. Есть идеи, как по-другому можно это организовать? Можно вспомнить пример из лекции по ОПП - Open-Closed Principle.

2024-06-03 18:13 UTC, vaganov-vadim commented on src/main/java/com/sabinaber/berezinabot/adapters/strategy/CommandType.java
> +public enum CommandType {
Есть ощущение, что в нашем случае этот enum и название самой команды практически равно. Может, в нём особо и нет смысла? Можем попробовать как-то связать название команды и логику обработки. Например, инкапсулировать в один класс. Как у тебя и сделано, только без enum =)

2024-06-03 18:14 UTC, vaganov-vadim commented
И переименуй PR под соглашение, пожалуйста, трудно сразу понять, о чём он.

2024-06-06 14:31 UTC, sabina-ber commented on src/main/java/com/sabinaber/berezinabot/BerezinaBotApplication.java
> +	private final Dotenv dotenv;
это библиотека, которую я нашла для хранения переменных окружения. они хранятся в корне проекта в файле с расширением .env и файл добавлен в .gitignore

2024-06-17 13:21 UTC, sabina-ber commented on src/main/java/com/sabinaber/berezinabot/adapters/bot/TelegramBot.java
> +        if (messageText.startsWith("/createuser")) {
исправила, добавив класс - обработик сообщений

2024-06-17 13:22 UTC, sabina-ber commented on src/main/java/com/sabinaber/berezinabot/adapters/strategy/CommandType.java
> +public enum CommandType {
убрала enum

2024-06-22 11:05 UTC, vaganov-vadim commented
@sabina-ber А что с PRкой случилось? У меня в изменениях один файл =(

2024-06-22 11:05 UTC, vaganov-vadim reviewed
Не понял, что случилось с ПРкой, у меня в изменениях остался только .gitignore.

2024-06-22 11:20 UTC, sabina-ber commented
> @sabina-ber А что с PRкой случилось? У меня в изменениях один файл =(

Я видимо намудрила со следующим заданием, где  нужно было разработать ci, влила туда ветку 3, потому что ci иначе  не запускался, а потом после проверки это все улетело в trunk, таким образом все изменения оказались сразу там и их не видно здесь? и что теперь делать?((

2024-06-25 12:34 UTC, sabina-ber commented
В ререквесте я заменила RestTemplate на более современный webClient

2024-06-25 16:00 UTC, vaganov-vadim commented
@sabina-ber ну то есть оно уже влито в trunk?

2024-06-25 16:00 UTC, vaganov-vadim approved these changes

2024-06-25 16:01 UTC, vaganov-vadim commented
Давай вливать, если что в следующих посмотрю, если что-то осталось неисправленным.

2024-06-25 16:07 UTC, sabina-ber commented
> @sabina-ber ну то есть оно уже влито в trunk?

да, оно влито после PR задания с ci :)

2024-06-25 16:53 UTC, closed without merging